const moteurDeRecherche = [
    'https://www.google.com/',
    'https://www.bing.com/',
    'https://duckduckgo.com/',
    'https://www.yahoo.com/',
    'https://www.facebook.com/',
    'https://www.twitter.com/',
    'https://www.instagram.com/',
    'https://www.reddit.com/',
    'https://www.youtube.com/',
    'https://www.wikipedia.org/',
    'https://www.amazon.com/',
    'https://www.ebay.com/',
    'https://www.apple.com/',
    'https://www.microsoft.com/',
    'https://www.netflix.com/',
    'https://www.paypal.com/',
    'https://www.stackoverflow.com/',
    'https://www.quora.com/',
    'https://www.github.com/',
    'https://www.medium.com/',
    'https://www.nytimes.com/',
    'https://www.cnn.com/',
    'https://www.foxnews.com/',
    'https://www.wsj.com/',
    'https://www.bbc.com/',
    'https://www.npr.org/',
    'https://www.reuters.com/',
    'https://www.cnbc.com/',
    'https://www.forbes.com/',
    'https://www.ft.com/',
    'https://www.businessinsider.com/',
    'https://www.huffpost.com/',
    'https://www.usatoday.com/',
    'https://www.bloomberg.com/',
    'https://www.theguardian.com/',
    'https://www.lemonde.fr/',
    'https://www.spiegel.de/',
    'https://www.elmundo.es/',
    'https://www.corriere.it/',
];


module.exports = { moteurDeRecherche };